name: Build & Test
on:
  push:
    branches: [ main, HashCalc ]
  pull_request:
    branches: [ main ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Examples.sln
    - name: Install Steam and Garry's Mod Dedicated Server
      run: |
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz
        rm -rfv steamcmd_linux.tar.gz
        ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit
    - name: Install GmodDotNet
      run: |
        wget https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodNETStorage/storage/gmod-dot-net-linux.0.7.0-beta.2.30293992.master.tar.gz -O gmoddotnet.tar.gz
        mkdir ./gmod/garrysmod/lua/bin
        tar -xvzf gmoddotnet.tar.gz -C ./gmod/garrysmod/lua/bin
        rm -rfv gmoddotnet.tar.gz
    - name: Build Module
      run: dotnet publish HashCalc/HashCalc.csproj --configuration Release --framework net5 -o ./gmod/garrysmod/lua/bin/Modules/HashCalc
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HashCalc linux-x64
        path: ./gmod/garrysmod/lua/bin/Modules/HashCalc/*
        retention-days: 10
    - name: Copy test.lua
      run: cp .github/workflows/test.lua ./gmod/garrysmod/lua/autorun
    - name: Run Garry's Mod
      run: ./srcds_run_x64 -game garrysmod -systemtest -condebug +sv_hibernate_think 1 || true
      working-directory: ./gmod/
      timeout-minutes: 1
      continue-on-error: true
    - name: Print log
      run: cat gmod/garrysmod/console.log
    - name: Tests successfull?
      uses: andstor/file-existence-action@v1
      with:
        files: "gmod/garrysmod/data/success.txt"
        allow_failure: true
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Examples.sln
    - name: Install Steam and Garry's Mod Dedicated Server
      shell: bash
      run: |
           curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -O -L
           powershell -Command 'Expand-Archive -LiteralPath ./steamcmd.zip -DestinationPath ./'
           ./steamcmd.exe +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit || true
    - name: Install GmodDotNet
      shell: bash
      run: |
        curl -o gmoddotnet.zip https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodNETStorage/storage/gmod-dot-net-windows.0.7.0-beta.2.30293992.master.zip -O -L
        mkdir ./gmod/garrysmod/lua/bin
        powershell -Command 'Expand-Archive -LiteralPath ./gmoddotnet.zip -DestinationPath ./gmod/garrysmod/lua/bin'
    - name: Build Module
      run: dotnet publish HashCalc/HashCalc.csproj --configuration Release --framework net5 -o ./gmod/garrysmod/lua/bin/Modules/HashCalc
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HashCalc win-x64
        path: ./gmod/garrysmod/lua/bin/Modules/HashCalc/*
        retention-days: 10
    - name: Copy test.lua
      run: cp .github/workflows/test.lua ./gmod/garrysmod/lua/autorun
    - name: Run Garry's Mod
      shell: bash
      run: |
           powershell -Command './gmod/srcds_win64.exe -console -systemtest -condebug -game "garrysmod" +exec "server.cfg" +gamemode sandbox +map gm_construct +maxplayers 16 +sv_hibernate_think 1'
           powershell -Command 'Wait-Process -Name srcds_win64'
      timeout-minutes: 1
      continue-on-error: true
    - name: Print log
      shell: bash
      run: cat gmod/garrysmod/console.log
    - name: Tests successfull?
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "gmod/garrysmod/data/success.txt"
        allow_failure: true
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Examples.sln
    - name: Build Module
      run: dotnet publish Examples.sln --configuration Release --framework net5
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HashCalc osx-x64
        path: HashCalc/bin/Release/net5/osx-x64/publish/*
        retention-days: 10
